name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  start-server:
    runs-on: self-hosted
    steps:
      - name: Start Server
        uses: ./.github/actions/start-server

  build-client:
    runs-on: self-hosted
    needs: start-server
    steps:
      - name: Start Server
        uses: ./.github/actions/start-server

  deploy:
    runs-on: self-hosted
    needs: build-client  # Wait for the client to build before deploying
    steps:
      - name: Deploy Build and Restart Services
        run: |
          # Build the application in a temporary directory to minimize downtime
          sudo mkdir -p /var/www/next_temp
          sudo cp -r ~/actions-runner/_work/Ai-Blog/Ai-Blog/.next /var/www/next_temp/
          sudo rm -rf /var/www/.next
          # Replace the old version with the new version
          sudo mv /var/www/next_temp/.next /var/www/.next
          # Remove temp directory
          sudo rm -rf /var/www/next_temp
          sudo systemctl reload nginx
          sudo systemctl restart nginx
