version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/500kalima
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
      environment:
        S3_BUCKET: '{{ssm:/500kalima/S3_BUCKET}}'
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
      environment:
        NODE_ENV: '{{ssm:/500kalima/NODE_ENV}}'
        DB_USERNAME: '{{ssm:/500kalima/DB_USERNAME}}'
        DB_PASSWORD: '{{ssm:/500kalima/DB_PASSWORD}}'
        DB_ROOT_PASSWORD: '{{ssm:/500kalima/DB_ROOT_PASSWORD}}'
        DB_NAME: '{{ssm:/500kalima/DB_NAME}}'
        DB_HOST: '{{ssm:/500kalima/DB_HOST}}'
        DB_PORT: '{{ssm:/500kalima/DB_PORT}}'
        MYSQL_SSL_CA: '{{ssm:/500kalima/MYSQL_SSL_CA}}'
        MYSQL_SSL_CERT: '{{ssm:/500kalima/MYSQL_SSL_CERT}}'
        MYSQL_SSL_KEY: '{{ssm:/500kalima/MYSQL_SSL_KEY}}'
        AWS_ACCESS_KEY_ID: '{{ssm:/500kalima/AWS_ACCESS_KEY_ID}}'
        AWS_SECRET_ACCESS_KEY: '{{ssm:/500kalima/AWS_SECRET_ACCESS_KEY}}'
        AWS_FILE_BUCKET: '{{ssm:/500kalima/AWS_FILE_BUCKET}}'
        AWS_REGION: '{{ssm:/500kalima/AWS_REGION}}'
        AWS_S3_OBJECT_BASEURL: '{{ssm:/500kalima/AWS_S3_OBJECT_BASEURL}}'
        JWT_SECRET: '{{ssm:/500kalima/JWT_SECRET}}'
        SALT_ROUNDS: '{{ssm:/500kalima/SALT_ROUNDS}}'
        PORT: '{{ssm:/500kalima/PORT}}'
        CLOUDFRONT_BASE_URL: '{{ssm:/500kalima/CLOUDFRONT_BASE_URL}}'
        CLOUDFRONT_KEY_PAIR_ID: '{{ssm:/500kalima/CLOUDFRONT_KEY_PAIR_ID}}'
        CLOUDFRONT_PRIVATE_KEY: '{{ssm:/500kalima/CLOUDFRONT_PRIVATE_KEY}}'
        API_URL: '{{ssm:/500kalima/API_URL}}'
