name: Backend CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      working-directory: server
      
    - name: Run Migrations
      env:
        NODE_ENV: production
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_FILE_BUCKET: ${{ secrets.AWS_FILE_BUCKET }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_OBJECT_BASEURL: ${{ secrets.AWS_S3_OBJECT_BASEURL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
        PORT: ${{ secrets.PORT }}
        CLOUDFRONT_BASE_URL: ${{ secrets.CLOUDFRONT_BASE_URL }}
        CLOUDFRONT_KEY_PAIR_ID: ${{ secrets.CLOUDFRONT_KEY_PAIR_ID }}
        CLOUDFRONT_PRIVATE_KEY: ${{ secrets.CLOUDFRONT_PRIVATE_KEY }}
      run: npm run migrate
      working-directory: server


    - name: Stop Previous PM2 Process if Exists
      run: |
        pm2 delete blog-backend || echo "No process named blog-backend found"

    - name: Start Application with PM2
      env:
        NODE_ENV: production
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_FILE_BUCKET: ${{ secrets.AWS_FILE_BUCKET }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_OBJECT_BASEURL: ${{ secrets.AWS_S3_OBJECT_BASEURL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
        PORT: ${{ secrets.PORT }}
        CLOUDFRONT_BASE_URL: ${{ secrets.CLOUDFRONT_BASE_URL }}
        CLOUDFRONT_KEY_PAIR_ID: ${{ secrets.CLOUDFRONT_KEY_PAIR_ID }}
        CLOUDFRONT_PRIVATE_KEY: ${{ secrets.CLOUDFRONT_PRIVATE_KEY }}
      run: pm2 start server/server.js --name "blog-backend"
