name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies (client)
        run: npm install

      - name: Install dependencies (server)
        run: |
          cd server
          npm install

      - name: Zip files
        run: zip -r 500kalima.zip .

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: aws s3 cp 500kalima.zip s3://${{ secrets.S3_BUCKET }}/500kalima.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2 via AWS SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          MYSQL_SSL_CA: ${{ secrets.MYSQL_SSL_CA }}
          MYSQL_SSL_CERT: ${{ secrets.MYSQL_SSL_CERT }}
          MYSQL_SSL_KEY: ${{ secrets.MYSQL_SSL_KEY }}
          AWS_FILE_BUCKET: ${{ secrets.AWS_FILE_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_OBJECT_BASEURL: ${{ secrets.AWS_S3_OBJECT_BASEURL }}
          JWT_SECRET: ${{secrets.JWT_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          PORT: ${{ secrets.PORT }}
          CLOUDFRONT_BASE_URL: ${{ secrets.CLOUDFRONT_BASE_URL }}
          CLOUDFRONT_KEY_PAIR_ID: ${{ secrets.CLOUDFRONT_KEY_PAIR_ID }}
          CLOUDFRONT_PRIVATE_KEY: ${{ secrets.CLOUDFRONT_PRIVATE_KEY }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=your-instance-name" --query "Reservations[*].Instances[*].InstanceId" --output text)
          aws ssm send-command \
            --instance-ids $INSTANCE_ID \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy 500kalima application" \
            --parameters commands='
              aws s3 cp s3://${{ secrets.S3_BUCKET }}/500kalima.zip /home/ubuntu/500kalima.zip;
              sudo unzip /home/ubuntu/500kalima.zip -d /home/ubuntu/500kalima;
              sudo rm -rf /home/ubuntu/500kalima.zip;

              cd /home/ubuntu/500kalima/server;
              npm run migrate:prod;

              pm2 start npm --name "server" -- start;

              cd /home/ubuntu/500kalima;
              ~/.nvm/versions/node/v22.2.0/bin/npm run build;
              pm2 start npm --name "client" -- start;

              pm2 save;
              pm2 startup;

              sudo systemctl reload nginx;
              sudo systemctl restart nginx;
            '