name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies (client)
        run: npm install

      - name: Install dependencies (server)
        run: |
          cd server
          npm install

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Deploy to EC2 via github action runner
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          MYSQL_SSL_CA: ${{ secrets.MYSQL_SSL_CA }}
          MYSQL_SSL_CERT: ${{ secrets.MYSQL_SSL_CERT }}
          MYSQL_SSL_KEY: ${{ secrets.MYSQL_SSL_KEY }}
          AWS_FILE_BUCKET: ${{ secrets.AWS_FILE_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_OBJECT_BASEURL: ${{ secrets.AWS_S3_OBJECT_BASEURL }}
          JWT_SECRET: ${{secrets.JWT_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          PORT: ${{ secrets.PORT }}
          CLOUDFRONT_BASE_URL: ${{ secrets.CLOUDFRONT_BASE_URL }}
          CLOUDFRONT_KEY_PAIR_ID: ${{ secrets.CLOUDFRONT_KEY_PAIR_ID }}
          CLOUDFRONT_PRIVATE_KEY: ${{ secrets.CLOUDFRONT_PRIVATE_KEY }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          cd server && \
          npm run migrate:prod && \
          cd .. && \
          npm run build && \
          pm2 restart all \
          sudo cp -rp /home/ubuntu/actions-runner/_work/Ai-Blog/Ai-Blog/.next /var/www/.next && \
          sudo systemctl reload nginx && \
          sudo systemctl restart nginx