name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies (client)
        run: |
          npm install

      - name: Install dependencies (server)
        run: |
          cd server
          npm install

      - name: Zip files
        run: zip -r 500kalima.zip .

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws s3 cp 500kalima.zip s3://${{ secrets.S3_BUCKET }}/500kalima.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to AWS CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          deployment_id=$(aws deploy create-deployment \
                          --application-name ${{ secrets.CODEDEPLOY_APPLICATION_NAME }} \
                          --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP_NAME }} \
                          --s3-location bucket=${{ secrets.S3_BUCKET }},key=500kalima.zip,bundleType=zip \
                          --query "deploymentId" --output text)

      - name: Wait for deployment to complete
        run: |
          aws deploy wait deployment-successful \
            --deployment-id $deployment_id \
            --region ${{ secrets.AWS_REGION }}
      
      - name: CD into the project server directory
        run: |
          cd home/ubuntu/500kalima/server

      - name: Run database migrations
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          MYSQL_SSL_CA: ${{ secrets.MYSQL_SSL_CA }}
          MYSQL_SSL_CERT: ${{ secrets.MYSQL_SSL_CERT }}
          MYSQL_SSL_KEY: ${{ secrets.MYSQL_SSL_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_FILE_BUCKET: ${{ secrets.AWS_FILE_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_OBJECT_BASEURL: ${{ secrets.AWS_S3_OBJECT_BASEURL }}
          JWT_SECRET: ${{secrets.JWT_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          PORT: ${{ secrets.PORT }}
          CLOUDFRONT_BASE_URL: ${{ secrets.CLOUDFRONT_BASE_URL }}
          CLOUDFRONT_KEY_PAIR_ID: ${{ secrets.CLOUDFRONT_KEY_PAIR_ID }}
          CLOUDFRONT_PRIVATE_KEY: ${{ secrets.CLOUDFRONT_PRIVATE_KEY }}
        run: |
          npm run migrate:prod

      - name: Start server
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          MYSQL_SSL_CA: ${{ secrets.MYSQL_SSL_CA }}
          MYSQL_SSL_CERT: ${{ secrets.MYSQL_SSL_CERT }}
          MYSQL_SSL_KEY: ${{ secrets.MYSQL_SSL_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_FILE_BUCKET: ${{ secrets.AWS_FILE_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_OBJECT_BASEURL: ${{ secrets.AWS_S3_OBJECT_BASEURL }}
          JWT_SECRET: ${{secrets.JWT_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          PORT: ${{ secrets.PORT }}
          CLOUDFRONT_BASE_URL: ${{ secrets.CLOUDFRONT_BASE_URL }}
          CLOUDFRONT_KEY_PAIR_ID: ${{ secrets.CLOUDFRONT_KEY_PAIR_ID }}
          CLOUDFRONT_PRIVATE_KEY: ${{ secrets.CLOUDFRONT_PRIVATE_KEY }}
        run: |
          pm2 start npm --name "server" -- start

      - name: Build client app (Next.js)
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          npm run build

      - name: Start client app
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          pm2 start npm --name "client" -- start

      - name: Save PM2 processes
        run: |
          pm2 save

      - name: Configure PM2 startup on system boot
        run: |
          pm2 startup

      - name: Reload and restart Nginx
        run: |
          sudo systemctl reload nginx
          sudo systemctl restart nginx