name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run deployment commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            eval "$(ssh-agent -s)" &&
            ssh-add ~/.ssh/github_AI_Blog &&
            cd blog && git pull &&
            source ~/.nvm/nvm.sh && nvm use v22.2.0 &&
            ~/.nvm/versions/node/v22.2.0/bin/npm i &&
            cd server && ~/.nvm/versions/node/v22.2.0/bin/npm i &&
            ~/.nvm/versions/node/v22.2.0/bin/npm run migrate &&
            cd .. && rm -rf .next && sudo rm -rf /var/www/.next &&
            npm run build && sudo cp -rp ~/blog/.next /var/www/.next &&
            pm2 restart 0 && pm2 restart 1 &&
            sudo systemctl reload nginx &&
            sudo systemctl restart nginx